---
title: 'pA status of cluster classes'
author: "Manfred Schmid"
output: 
  pdf_document:
    toc: true 
    toc_depth: 3
    fig_caption: true
editor_options: 
  chunk_output_type: console
---

`r format(Sys.time(), "%d %B, %Y; %R")`

## Setup


```{r setup, echo=TRUE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, 
                      fig.path='../../Figures/cluster_pAstatus/', 
                      dev='pdf', 
                      echo=TRUE, warning=FALSE, message=FALSE, 
                      error=TRUE)
```


```{r load packages, echo=T, warning=F, message=F}
suppressWarnings(library('tidyverse'))
suppressWarnings(library('magrittr'))
suppressWarnings(library('knitr'))
suppressWarnings(library('broom'))
```



#### load last exon counts for comparison

```{r, eval=TRUE}
load('../../data/last_exon_counts_July_Sept_Nov.RData', verbose=TRUE)
(last_exon_mat <- df %>%
    tidyr::separate(series, c('month', 'rep'), sep='x') %>%
    tidyr::unite(library, c(month, siRNA, PAP, fraction, rep), sep='_') %>%
    mutate(library = sub('_NA', '', library)))
```

```{r}
last_exon_mat %<>%
  tidyr::spread(library, sum) %>%
  data.frame %>%
  column_to_rownames('name')

head(last_exon_mat)
```


#### load cluster counts (see DESeq2)
```{r}
load('../../data/count_mat_RRP40Z1Z8clusters.RData', verbose=TRUE)
head(count_mat)
```



#### load and adjust size factor naming

```{r}
(nfs <- read_tsv('../../data/last_exon_sizeFactors.table'))
```

```{r}
(nfs %<>%
  mutate(full_lib_name = paste0(series, '_', lib_name)) %>%
  dplyr::select(full_lib_name, geom_mean_sf, sizeFactor, spike_sf))
```

```{r}
!(colnames(last_exon_mat) %in% nfs$full_lib_name)
```

```{r}
!(colnames(count_mat) %in% nfs$full_lib_name)
```


```{r}
(last_exon_df <- last_exon_mat %>%
  rownames_to_column('cluster') %>%
  gather(full_lib_name, cnt, -cluster) %>%
  tbl_df)
```

```{r}
(cnt_df <- count_mat %>%
  data.frame %>% 
  rownames_to_column('cluster') %>%
  gather(full_lib_name, cnt, -cluster) %>%
  tbl_df)
```


```{r}
(norm_last_exon_df <- last_exon_df %>%
  left_join(., nfs) %>%
  mutate(norm_cnt = cnt/geom_mean_sf) %>%
  dplyr::select(cluster, full_lib_name, norm_cnt) %>%
  tidyr::separate(full_lib_name, c('series', 'siRNA', 'PAP', 'fraction', 'rep'), sep='_') %>%
  group_by(cluster, siRNA, fraction, PAP) %>%
  summarise(norm_cnt = mean(norm_cnt)))
```


```{r}
(norm_cnt_df <- cnt_df %>%
  left_join(., nfs) %>%
  mutate(norm_cnt = cnt/geom_mean_sf) %>%
  dplyr::select(cluster, full_lib_name, norm_cnt) %>%
  tidyr::separate(full_lib_name, c('series', 'siRNA', 'PAP', 'fraction', 'rep'), sep='_') %>%
  group_by(cluster, siRNA, fraction, PAP) %>%
  summarise(norm_cnt = mean(norm_cnt)))
```


## classification into PAXT vs NEXT
```{r}
load('../../data/cluster_classes.RData', verbose=T)
cluster_classes
```

```{r}
(norm_cnt_df %<>% left_join(., cluster_classes))
```

```{r}
norm_cnt_df %<>%
  ungroup %>%
  mutate(siRNA = factor(siRNA, levels=c('siGFP', 'siRRP40', 'siZCCHC8', 'siZFC3H1', 'siZCCHC8.ZFC3H1')))
```



## library comparisons

```{r}
last_exon_rel_lib <- norm_last_exon_df %>%
  ungroup %>%
  group_by(cluster, siRNA, PAP, fraction) %>%
  summarise(mean_cnt = mean(norm_cnt)) %>%
  group_by(cluster, siRNA) %>%
  mutate(norm_cnt_per_lib = mean_cnt/sum(mean_cnt))
```

```{r}
rel_lib <- norm_cnt_df %>%
  ungroup %>%
  filter(class == 'PAXT' | class == 'NEXT') %>%
  group_by(cluster, siRNA, PAP, fraction, class) %>%
  summarise(mean_cnt = mean(norm_cnt)) %>%
  group_by(cluster, siRNA, class) %>%
  mutate(norm_cnt_per_lib = mean_cnt/sum(mean_cnt))
```



```{r last exon rel libtype boxplot}
#pdf('last exon rel libtype boxplot.pdf')
last_exon_rel_lib %>%
  mutate(PAP_fraction = paste0(fraction, '_', PAP)) %>%
ggplot(., aes(x=PAP_fraction, y=norm_cnt_per_lib, fill=PAP_fraction)) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(.~siRNA) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
#dev.off()
```


```{r rel libtype boxplot}
rel_lib %>%
  mutate(PAP_fraction = paste0(fraction, '_', PAP)) %>%
ggplot(., aes(x=PAP_fraction, y=norm_cnt_per_lib, fill=PAP_fraction)) +
  geom_boxplot(outlier.shape = NA) +
  facet_grid(class~siRNA) +
  theme_bw() +
  theme(panel.grid=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r rel lib violin boxplot}
rel_lib %>%
  mutate(PAP_fraction = paste0(fraction, '_', PAP)) %>%
ggplot(., aes(x=siRNA, y=norm_cnt_per_lib, fill=siRNA)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, fill='lightgray', width=.1) +
  facet_grid(PAP_fraction~class, scales='free') +
  theme_bw() +
  theme(panel.grid=element_blank(),
        axis.text.x=element_text(angle=45, hjust=1))
```

```{r rel lib violin barplot swapped}
rel_lib %>%
  mutate(PAP_fraction = paste0(fraction, '_', PAP)) %>%
ggplot(., aes(x=siRNA, y=norm_cnt_per_lib, fill=siRNA)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, fill='lightgray', width=.1) +
  facet_grid(PAP_fraction~class, scales='free') +
  theme_bw() +
  theme(panel.grid=element_blank(),
        axis.text.x=element_text(angle=45, hjust=1))
```



## pAness


```{r}
(last_exon_pAness <- norm_last_exon_df %>%
  spread(PAP, norm_cnt) %>%
   ungroup %>%
  mutate(pAratio = noPAP/xPAP,
         pAness = ifelse(pAratio > 1, 1, pAratio),
         siRNA = factor(siRNA, levels=c('siGFP', 'siRRP40', 'siZCCHC8', 'siZFC3H1', 'siZCCHC8.ZFC3H1'))))
```


```{r}
(pAness <- norm_cnt_df %>%
   spread(PAP, norm_cnt) %>%
   ungroup %>%
  mutate(pAratio = noPAP/xPAP,
         pAness = ifelse(pAratio > 1, 1, pAratio),
         siRNA = factor(siRNA, levels=c('siGFP', 'siRRP40', 'siZCCHC8', 'siZFC3H1', 'siZCCHC8.ZFC3H1'))))
```

```{r}
pAness %<>%
  mutate(class = factor(class, levels=c('PAXT', 'NEXT', 'BOTH', 'NOT_SIG')))
```


```{r last exon pAness violin barplot}
ggplot(last_exon_pAness, aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, width=.1, fill='gray') +
  facet_grid(fraction~.) +
  coord_cartesian(ylim=c(0,1.5)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r pAness violin barplot}
ggplot(pAness, aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, width=.1, fill='gray') +
  facet_grid(fraction~class) +
  coord_cartesian(ylim=c(0,1.5)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))

```


#### add counts to plot

```{r}
(group_n <- pAness %>%
   filter(!is.na(pAness)) %>%
  group_by(siRNA, class,fraction) %>%
  summarize(cnt=n(),
            median=median(pAness)))
```

```{r pAness violin barplots with counts and medians}
pAness %>%
  ggplot(., aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin() +
  geom_boxplot(outlier.shape = NA, width=.1, fill='gray') +
  facet_grid(fraction~class) +
  coord_cartesian(ylim=c(0,1.5)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(data=group_n, aes(x=siRNA, y=1.1, label=round(median, 2)), angle=45, size=3) +
  geom_text(data=group_n, aes(x=siRNA, y=1.3, label=cnt), angle=45, size=3)
```

```{r pAness violin barplot without notsig}
pAness %>%
  filter(class != 'NOT_SIG') %>%
  ggplot(., aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin(scale = 'width') +
  geom_boxplot(outlier.shape = NA, width=.2, fill='gray') +
  facet_grid(fraction~class) +
  coord_cartesian(ylim=c(0,1.5)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(data=filter(group_n, class != 'NOT_SIG'), aes(x=siRNA, y=1.1, label=round(median, 2)), angle=45, size=3) +
  geom_text(data=filter(group_n, class != 'NOT_SIG'), aes(x=siRNA, y=1.3, label=cnt), angle=45, size=3)
```


#### pAness stats
```{r}
(stats <- pAness %>%
  group_by(siRNA, class,fraction) %>%
  do(tidy(summary(.$pAness))))
```


```{r}
stats %>% 
  dplyr::select(siRNA, class, fraction, median) %>%
  spread(siRNA, median)
```

```{r }
stats %>% 
  dplyr::select(-cnt) %>%
  spread(siRNA, median)
```



#### only clusters present in xPAP of all knockdowns


```{r}
(cluster_with_xPAP_signal <- pAness %>%
  filter(xPAP > 0) %>%
  group_by(cluster) %>%
  summarize(cnt = n()))
```


```{r}
(cluster_with_xPAP_signal_in_all_libs <- filter(cluster_with_xPAP_signal, cnt == 10))
```


```{r}
(pAness_sameset <- pAness %>%
   filter(class != 'NOT_SIG') %>%
   left_join(., cluster_with_xPAP_signal_in_all_libs) %>%
   filter(cnt == 10))
```

```{r}
table(pAness_sameset$class)
```


```{r pAness violinplot same set}
ggplot(pAness_sameset, aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin(scale='width', draw_quantiles = c(.5)) +
  #geom_boxplot(outlier.shape = NA, width=.15, fill='gray') +
  facet_grid(fraction~class) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r pAness violinboxplot same set}
ggplot(pAness_sameset, aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin(scale='width') +
  geom_boxplot(outlier.shape = NA, width=.1, fill='gray') +
  facet_grid(fraction~class) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r}
group_n_sameset <- pAness_sameset %>%
  filter(!is.na(pAness)) %>%
  group_by(siRNA, class,fraction) %>%
  summarize(median = median(pAness),
            cnt=n())
```

```{r}
group_n_sameset %>% 
  dplyr::select(-median) %>%
  spread(siRNA, cnt)
```

```{r }
group_n_sameset %>% 
  dplyr::select(-cnt) %>%
  spread(siRNA, median)
```


```{r pAness violin boxplot floored at 1 with counts same set}
ggplot(pAness_sameset, aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin(scale='width') +
  geom_boxplot(outlier.shape = NA, width=.1, fill='gray') +
  facet_grid(fraction~class) +
  coord_cartesian(ylim=c(0,1.5)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(data=group_n_sameset, aes(x=siRNA, y=1.1, label=round(median, 2)), angle=45, size=3) +
  geom_text(data=distinct(group_n_sameset,class,fraction, cnt), aes(x=2, y=1.3, label=paste0('n=',cnt)), size=3)
```

```{r pAness violinplot floored at 1 with counts same set}
ggplot(pAness_sameset, aes(x=siRNA, y=pAness, fill=siRNA)) +
  geom_violin(scale='width', draw_quantiles = 0.5) +
  facet_grid(fraction~class) +
  coord_cartesian(ylim=c(0,1.5)) +
  theme_bw() +
  theme(panel.grid=element_blank()) +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  geom_text(data=group_n_sameset, aes(x=siRNA, y=1.1, label=round(median, 2)), angle=45, size=3) +
  geom_text(data=distinct(group_n_sameset,class,fraction, cnt), aes(x=2, y=1.3, label=paste0('n=',cnt)), size=3)
```




#### Wilcox pvalues KD higher than control

```{r}
pAness_sameset %>%
  dplyr::select(cluster, siRNA, fraction, class, pAness) %>%
  spread(siRNA, pAness) %>%
  group_by(class, fraction) %>%
  do(tidy(wilcox.test(.$siZCCHC8, .$siGFP, alternative = 'greater', paired=T,conf.int = T)))
```

```{r}
pAness_sameset %>%
  dplyr::select(cluster, siRNA, fraction, class, pAness) %>%
  spread(siRNA, pAness) %>%
  group_by(class, fraction) %>%
  do(tidy(wilcox.test(.$siRRP40, .$siGFP, alternative = 'greater', paired=T,conf.int = T)))
```

```{r}
pAness_sameset %>%
  dplyr::select(cluster, siRNA, fraction, class, pAness) %>%
  spread(siRNA, pAness) %>%
  group_by(class, fraction) %>%
  do(tidy(wilcox.test(.$siZFC3H1, .$siGFP, alternative = 'greater', paired=T,conf.int = T)))
```

```{r}
pAness_sameset %>%
  dplyr::select(cluster, siRNA, fraction, class, pAness) %>%
  spread(siRNA, pAness) %>%
  group_by(class, fraction) %>%
  do(tidy(wilcox.test(.$siZCCHC8.ZFC3H1, .$siZCCHC8, alternative = 'greater', paired=T,conf.int = T)))
```


## sessionInfo
```{r}
sessionInfo()
```
